version: "3.8"

services:
  airflow:
    build:
      context: ./airflow
    container_name: airflow-locust
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    volumes:
      - ./airflow:/opt/airflow/dags
      - .:/opt/airflow/project
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --firstname Admin --lastname User
               --role Admin --email admin@example.com --password admin &&
               airflow webserver & airflow scheduler"

