apiVersion: batch/v1
kind: Job
metadata:
  name: locust-loadtest
spec:
  template:
    spec:
      containers:
      - name: locust
        image: locust:latest
        command: ["locust"]
        args:
          - "-f"
          - "/locust/locustfile.py"
          - "--headless"
          - "--host=http://mock-api-service:8000"
          - "--users=50"
          - "--spawn-rate=5"
          - "--run-time=2m"
          - "--tags=load"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
      restartPolicy: Never